### ISSUE TITLE
description for BATTERY VOLTAGE

### ISSUE THREAD

**Issue by pfps** [Logitech/cpg-docs#10]
Although I've implemented support for BATTERY VOLTAGE in Solaar based on existing Solaar code and some information in the Linux kernel it would be useful to have official documentation on this feature, and maybe voltage vs capacity tables as well.

**Comment by xnlcasad** [comment]
Can you clarify which feature number you'd need info ?

**Comment by pfps** [comment]
Sorry, feature 0x1001.
