### ISSUE TITLE
Documentation for Persistent remappable action {1C00}

### ISSUE THREAD

**Issue by adatum** [Logitech/cpg-docs#14]
Request for documentation to implement the `PERSISTENT_REMAPPABLE_ACTION (0x1C00)` feature for feature request https://github.com/pwr-Solaar/Solaar/issues/832 as per https://github.com/pwr-Solaar/Solaar/issues/582

**Comment by xnlcasad** [comment]
@pfps Now available on the shared google drive. Appreciate any help to convert it to this site's format for uniformity.

**Comment by pfps** [comment]
Excellent.  Thanks.  This is not a simple feature so getting into rst may take a while.

**Comment by xnlcasad** [comment]
Yeah, totally, my comment was just a general one.

**Comment by pfps** [comment]
Boring meetings are good for some things, notably simple work like reformatting documents. 
Today was quite boring.

**Comment by pfps** [comment]
@xnlcasad The documentation refers to a usage document, e.g. in
```
actionId
8-bit unsigned representing the action that has to be performed by the device.
0x01 - send keyboard/keypad report (usage page 7)
0x02 - send mouse button report (usage page 9)
0x03 - send X displacement (usage page 1, code 0x30)
0x04 - send Y displacement (usage page 1, code 0x31)
0x05 - send vertical roller/wheel displacement (usage page 1, code 0x38)
0x06 - send horizontal roller/AC pan displacement (usage page 12, code 0x0238)
0x07 - send consumer control report (usage page 12)
0x08 - execute internal funtion (use value parameter as function index)
0x09 - send power key report (usage page 1)
```
I can figure out the keyboard, mouse, and scroll ones, but I'm stumped on the consumer control reports.  Is there documentation for them?

**Comment by xnlcasad** [comment]
https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf ?

**Comment by pfps** [comment]
That has the information, thanks.
