### ISSUE TITLE
Request documentation on reserved receiver fields in HID++1.0 fields

### ISSUE THREAD

**Issue by pfps** [Logitech/cpg-docs#2]
Some fields in receiver registers and notifications are marked as reserved in the HID++ documentation but appear to be used in later protocols and are important in pairing.   Documentation on these fields would allow for the creation of better pairing tools.  In particular fields r5, r6, and r8 of record B5 with nn looking like 0x2y and error type 0x04 and field r2 of notification 4A appear of interest.

**Comment by FFY00** [comment]
Here's the updated documentation for the error in the `0x4A` notification.

```
0x00 = no error
0x01 = timeout
0x02 = unsupported device
0x03 = too many devices
0x04 = RCV out of pairing memory
0x05 = DVC out of pairing memory
0x06 = connection sequence timeout
0x07..0xFF: Rerserved
```

**Comment by pfps** [comment]
Well if that's all we can get we'll have to soldier along, but it would be nice to get an updated version of the old hid++ 1.0 for receivers documentation.

**Comment by FFY00** [comment]
I think it's easier if we track down a specific issue.

**Comment by pfps** [comment]
OK, here are two///threee/////four////five (cue Monty Python Spanish Inquisition skit):
1/ Different receivers have different maximum number of paired devices.   For some receivers this information appears to be in register 0xB503 byte 6.  Solaar uses this undocumented register field.  Some receivers do not implement this register but appear to have the information in 0xB510 byte 6.  Having these guesses confirmed would allow for better control of pairing.
2/ The serial number of some receivers is in register 0xB503 bytes 1 through 4.  Solaar uses this undocumented register field.  Some receivers appear to have their serial number in register 0xB510 bytes 1 through 4.  Having these guesses confirmed would allow for better control of pairing.
3/ It would be useful to have a documented correct way of determining whether a receiver is a Unifying receiver, a Lightspeed receiver, or a Nano receiver.  Solaar uses some heuristics for this that might be wrong.
4/ Some receivers have a maximum number of successful pairings.  The number of remaining pairings (plus 5) appears to be in register 02 byte 2 for these receivers.  It would be useful to have this guess confirmed.
5/ Some receivers cannot unpair.  Instead pairing replaces an existing pairing to the same kind of device if such a pairing exists.  It would be useful to have a documented way of determining for which devices this is the case.
