### ISSUE TITLE
What exactly is host-mode?

### ISSUE THREAD

**Issue by qodroi** [Logitech/cpg-docs#20]
I came across Set Report Rate (x8060), and the doc mentions that _this function can be called only in host mode_. Any clue what that means?

It seems like it prevents me from setting a new report rate, even when the request I issue is fully valid, Invalid Argument is returned. 

Errors
- _[InvalidArgument (2) Invalid reportRate, not in host mode]_

**Comment by pfps** [comment]
Your device should have a feature ONBOARD PROFILES 0x8100 which allows software to set up a profile and switch the device between profiles.  Profiles can include lots of device settings, including the report rate.  This feature can also set the device to host mode, where none of the profiles are active but enables other features.

**Comment by qodroi** [comment]
> Your device should have a feature ONBOARD PROFILES 0x8100 which allows software to set up a profile and switch the device between profiles. Profiles can include lots of device settings, including the report rate. **This feature can also set the device to host mode, where none of the profiles are active but enables other features.**

By _where none of the profiles are active but enables other features_, you mean that setting device's report rate when multiple on-board memory profiles are activated, is illegal?

**Comment by pfps** [comment]
The device can have one of the onboard profiles active, or no onboard profile active.  The latter is called host mode.  In host mode features that provide facilities that overlap with those provided by the profiles can be used to change these facilities.   (Sorry for being a bit abstract but different devices might have different features and facilities.  One of the facilities that is often controlled by onboard profiles or by a separate feature is the report rate.)  So on many devices the report rate feature can only be used to change the report rate when the device's onboard profiles feature is in host mode.

If you are running Linux you could install Solaar https://github.com/pwr-Solaar/Solaar and disable onboard profiles to be able to change the report rate.
