### ISSUE TITLE
description for REMAINING_PAIRING (0x1DF0)

### ISSUE THREAD

**Issue by pfps** [Logitech/cpg-docs#3]
I'm going to try to implement REMAINING_PAIRING (0x1DF0) but I will need documentation.

**Comment by pfps** [comment]
Hmm, maybe I can't try to implement, as this seems to be for devices, not receivers.  I'm interested in good documentation on the remaining pairings for c534 receivers.  Do receivers even have HID++ 2.0 features?  Solaar doesn't seem to report them.

**Comment by xnlcasad** [comment]
I'll get in touch with @FFY00 so that we can give you the relevant info.

**Comment by xnlcasad** [comment]
@pfps Can we close this ?

**Comment by pfps** [comment]
Yes.
