### ISSUE TITLE
description for VERTICAL_SCROLLING (0x2100) and MOUSE_POINTER (0x2200)

### ISSUE THREAD

**Issue by pfps** [Logitech/cpg-docs#4]
These two features are listed as implemented for Solaar, but there is no way to change the information for them.   Are these read-only?  If not, if I get documentation I can try to implement changes for them as I have a mouse that has these features.

**Comment by xnlcasad** [comment]
I'll get in touch with @FFY00 so that we can give you the relevant info.

**Comment by xnlcasad** [comment]
Both features are read only and deprecated.

**Comment by pfps** [comment]
OK
