### ISSUE TITLE
HID++ 4.x protocol and Logitech G533

### ISSUE THREAD

**Issue by kdomanski** [Logitech/cpg-docs#5]
Hi,
thanks for publishing the HID++ 2.0 specs. I recently purchased a G533 gaming headset and would like to extend existing Linux tools for Logitech devices (e.g. Solaar) with support for that device. The headset reports to be using HID++ 4.2 protocol - please add the corresponding documentation to this repo.

I have already written some code for fetching the battery voltage using feature 0x1F20, but I have additional questions:
- is there a way to force the headset report its voltage without polling, the way it currently automatically reports changes in its charging state?
- how exactly is the battery percentage determined based on the voltage in Logitech's Window app? if a table conversion is used, please publish the table as well

Regards,
Kamil Domański

**Comment by FFY00** [comment]
As you can see in https://github.com/Logitech/cpg-docs/blob/master/hidpp20/features/0x0000-IRoot.rst#getprotocolversion, your device is actually speaking HID++ 2.0. The old documentation is misleading.

I don't think `0x1F20` has anything to do with the battery, but I may be wrong, where did you get that from?

Can you post the list of features supported by your device? You can use the Root feature to get it.

**Comment by kdomanski** [comment]
>As you can see in https://github.com/Logitech/cpg-docs/blob/master/hidpp20/features/0x0000-IRoot.rst#getprotocolversion, your device is actually speaking HID++ 2.0. The old documentation is misleading.

Ah, I see. The 0x04 for version 2 is quite misleading indeed. Since the device returns 0x04 for major and 0x02 for minor, that would mean the protocol in use is 2.2, right?

> I don't think 0x1F20 has anything to do with the battery, but I may be wrong, where did you get that from?

The code is used by https://github.com/ashkitten/g933-utils/, a library for the G933 which is mostly similar to the G533. It was also on the list at https://github.com/pwr-Solaar/Solaar/issues/582 until you edited it and removed the code from the list 2 minutes before writing this comment.

> Can you post the list of features supported by your device? You can use the Root feature to get it.
```
feature 0x01, index 01
feature 0x03, index 02
feature 0x05, index 03
feature 0x1F20, index 07
feature 0x8010, index 04
feature 0x8300, index 06
feature 0x8310, index 05
```

**Comment by xnlcasad** [comment]
@kdomanski is it OK to close this issue ?
