### ISSUE TITLE
KEYBOARD_DISABLE_KEYS and GESTURE_2 

### ISSUE THREAD

**Issue by pfps** [Logitech/cpg-docs#8]
https://github.com/pwr-Solaar/Solaar/pull/788 reverse engineers KEYBOARD_DISABLE_KEYS and GESTURE_2 but it would be nice to have documentation to validate that the code works for other devices.   Implementing GESTURE would be a nice addition so documentation for that would be useful.

**Comment by FFY00** [comment]
@xnlcasad can we get Peter the documentation for this?

**Comment by xnlcasad** [comment]
Yes, I can share that documentation, let's start with disable keys (0x4521), but it would be nice if we can get a PR with the .rst in the right format so that we have it once and for all published properly.

**Comment by pfps** [comment]
If you send me ASCII (or just about anything else) I should be able to massage it into rst.
